Error: Exception in thread "main" java.lang.NullPointerException:
Cannot evoke

Cause : WordManager.java -23 : void WordManger(){
wordCRUD = new WordCRUD(s); }
WordManager function is executed, you have to declare that wordCRUD =
new WordCRUD, but if you prepend it with void it will execute like a
normal function without a return value and the value of wordCRUD will be
null. An error has occurred because it has become.